package com.wordpress.binarycoders;

/**
 * Even Fibonacci numbers
 *
 * Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Problem2 {

	private static final int LIMIT = 4000000;

	public static void main(String[] args) {
		System.out.println(Problem2.solve());
	}

	private static long solve() {
		int total = 0;
		int a = 1;
		int b = 1;
		int tmp;

		while (b < LIMIT) {
			if (b % 2 == 0) {
				total += b;
			}

			tmp = a + b;
			a = b;
			b = tmp;
		}

		return total;
	}
}
